### ISSUE TITLE
Idea: Timer for speaker

### ISSUE THREAD

**Issue by qaiser42** [c-base/hackandtell-raspberry#4]
I noticed (also when I gave talks at Berlin Hack and Tell in the past) that speaker tend to loose track of time during their presentation because they don't see the timer on their very right.
I think it would be helpful if there was an additional timer visible _just_ for the speaker.

=> I would be happy to work on a hack but wasn't too sure how to connect a new display? Is it really just adding a new output similar to https://github.com/c-base/hackandtell-raspberry/blob/master/src/ofApp.cpp#L12?

It would be great if we could collaborate on this idea!

**Comment by lucasrangit** [comment]
Hi @qabbasi , you're right about the timer placement. 

The code at https://github.com/c-base/hackandtell-raspberry/blob/master/src/ofApp.cpp#L12 is for the applause light. Not the matelight.

Do you want to build a new matelight or add the code to communicate with a new display type?

Either way, send an email to the BHNT team mail@berlinhackandtell.rocks so we can discuss further. If there's a specific issue with the current timer software we can open ticket here later.

Thanks for the feedback and for presenting your hacks!

**Comment by qaiser42** [comment]
Thanks for your response. Alright, I will email the BHNT team and would close this issue as of now.
